### ISSUE TITLE
How to take word order into account?

### ISSUE THREAD

**Issue by insomnia1996** [complementizer/rl-sentence-compression#1]
Hi, thanks for your great work and your code as well! I noticed that you didn't change the word order extracted from the source sentence, so I was just wondering can I use some reward to control the word order of the summarization, since extractive method does not consider this. Do you have any suggestion on my confusion? Thanks in advance!

**Comment by complementizer** [comment]
Hi, thanks for the question and sorry for the delayed answer! The model format/architecture I used (binary sequence labelling) only extracts words in their original order. To extract words and output them in a different order, you would need a different architecture, e.g. a pointer network. The same reward functions should work either way though, it actually doesn't even matter for them whether source and output words overlap!

**Comment by insomnia1996** [comment]
> Hi, thanks for the question and sorry for the delayed answer! The model format/architecture I used (binary sequence labelling) only extracts words in their original order. To extract words and output them in a different order, you would need a different architecture, e.g. a pointer network. The same reward functions should work either way though, it actually doesn't even matter for them whether source and output words overlap!

Thanks a lot for your reply, I'll try it later!
